HW01
================
Hubert Chang
2026-09-26

\#Problem 1

\##Summary

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim_variable | n_missing | complete_rate | ordered | n_unique | top_counts |
|:---|---:|---:|:---|---:|:---|
| species | 0 | 1.00 | FALSE | 3 | Ade: 152, Gen: 124, Chi: 68 |
| island | 0 | 1.00 | FALSE | 3 | Bis: 168, Dre: 124, Tor: 52 |
| sex | 11 | 0.97 | FALSE | 2 | mal: 168, fem: 165 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| bill_length_mm | 2 | 0.99 | 43.92 | 5.46 | 32.1 | 39.23 | 44.45 | 48.5 | 59.6 | ▃▇▇▆▁ |
| bill_depth_mm | 2 | 0.99 | 17.15 | 1.97 | 13.1 | 15.60 | 17.30 | 18.7 | 21.5 | ▅▅▇▇▂ |
| flipper_length_mm | 2 | 0.99 | 200.92 | 14.06 | 172.0 | 190.00 | 197.00 | 213.0 | 231.0 | ▂▇▃▅▂ |
| body_mass_g | 2 | 0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year | 0 | 1.00 | 2008.03 | 0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

species, island, bill_length_mm, bill_depth_mm, flipper_length_mm,
body_mass_g, sex, year varaible names

2007 data year span 2009

344 number of rows 8 number of columns

200.92 mean of flipper length in mm

### scatter plot of flipper length

``` r
ggplot (penguins, aes (x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_tc3524_files/figure-gfm/scatterplot-1.png)<!-- -->

``` r
ggsave ("hw01_scatterplot.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

\#Problem 2

## Creating Data Frame

``` r
library (tidyverse)

set.seed(1234)

problem2_df = tibble( 
  norm_samp = rnorm(10), #random sampe of size of 10
  norm_gt_zero = norm_samp > 0, #indicating that elements of the sample are greater than 0
  char_vec = c("Green", "Black", "Oolong", "Chamomile", "Matcha", "Chai", "Masala", "Herbal", "Hibiscus", "Ginger"), #character vector of length 10 characters
  factor_vec = factor(c("low", "medium", "high", "high", "medium", "low", "medium", "high", "high", "low")) #factor vector of 10 length that show 3 different levels
)

problem2_df
```

    ## # A tibble: 10 × 4
    ##    norm_samp norm_gt_zero char_vec  factor_vec
    ##        <dbl> <lgl>        <chr>     <fct>     
    ##  1    -1.21  FALSE        Green     low       
    ##  2     0.277 TRUE         Black     medium    
    ##  3     1.08  TRUE         Oolong    high      
    ##  4    -2.35  FALSE        Chamomile high      
    ##  5     0.429 TRUE         Matcha    medium    
    ##  6     0.506 TRUE         Chai      low       
    ##  7    -0.575 FALSE        Masala    medium    
    ##  8    -0.547 FALSE        Herbal    high      
    ##  9    -0.564 FALSE        Hibiscus  high      
    ## 10    -0.890 FALSE        Ginger    low

\#calculating the mean of the variables

``` r
mean (pull (problem2_df, norm_samp))
```

    ## [1] -0.3831574

``` r
mean (pull (problem2_df, norm_gt_zero))
```

    ## [1] 0.4

``` r
mean (pull (problem2_df, char_vec))
```

    ## Warning in mean.default(pull(problem2_df, char_vec)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
mean (pull (problem2_df, factor_vec))
```

    ## Warning in mean.default(pull(problem2_df, factor_vec)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

## 

The mean of the sample is -0.38 this worked because it is a numerical
value The mean for logical vector indicator is 0.4 this worked because
it is also a numerical value The mean for character value is NA because
it is not a numerical value The mean for factor vector is also NA
because it is not a numerical value.

### Converting character values into numeric value

``` r
as.numeric (pull(problem2_df, norm_gt_zero))
```

    ##  [1] 0 1 1 0 1 1 0 0 0 0

``` r
as.numeric (pull(problem2_df, char_vec))
```

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric (pull(problem2_df, factor_vec))
```

    ##  [1] 2 3 1 1 3 2 3 1 1 2

When using as.numeric, we could see that it worked on logical vector and
factor vector, but it would not work for character vector. It does
explain what happens when taking the mean. In logical vector, it
calculates the mean of 1 and 0s to see if they are true or false, so it
can calculate to see the proportions of them. In character vector, it is
text strings so it cannot be converted to number. In factor vector, it
made them into categories in terms of numbers, so they do not calculate
since it is a category.
